print("Nama : Nazlha Noor Aiena Sofhie")
print("Nim : 20210801281")
print("Jurusan : Teknik Informatika")
print("===================================")
print("PROGRAM QUIZ")
print("=====================================")
nama = input("\nMasukkan Nama: ")
NIM = input ("Masukkan NIM: ")
print("\nNama: " + str(nama))
print("NIM: " + str (NIM))
